# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: pmarsceill/just-the-docs@v0.3.3
url: "https://ece101.0xsk.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# everything beyond this point is common across all configs

title: ECE 101
tagline: Exploring Digital Information Technologies for Non-Engineers
description: ""
author: Shreyas Kishore
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "readme.md", "CNAME", "build_and_push_uiuc.sh"]

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links_new_tab: true
aux_links:
  slack:
    title: 'Slack' 
    link: 'https://ece101workspace.slack.com/'
    show: true
  canvas:
    title: 'Grades'
    link: 'https://canvas.illinois.edu/'
    show: true
  zoom_lec:
    title: 'Live Lecture (Zoom)'
    link: 'https://illinois.zoom.us/j/89291413832?pwd=TTlrdktPVGxFUFVWaVA3bDRjRVM4dz09'
    show: true
  zoom_lab:
    link: 'https://illinois.zoom.us/j/89291413832?pwd=TTlrdktPVGxFUFVWaVA3bDRjRVM4dz09'
  recordings:
    title: 'Recorded Lectures'
    link: '#calendar'
    show: true
footer_content: 'ECE 101 Website for Spring 2022 <br /> Based on <a href="https://github.com/kevinlin1/just-the-class">Just the Class</a> and powered by <a href="https://jekyllrb.com/">Jekyll</a> <br /> Source code available <a href="https://github.com/0xsk/ece101-website">here</a>'
back_to_top: true
back_to_top_text: "Back to top"
nav_sort: case_sensitive

# Collections for website data
collections:
  staffers:
  modules:
  schedule:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
